version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/**Module"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/**Module"
    schedule:
      interval: "weekly"
