name: Create Release

on:
  push:
    branches:
      - v3
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip each folder
        run: |
          for d in */ ; do
            zip -r "${d%/}.zip" "$d"
          done

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Release
        uses: MarvinPinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}-${{ github.sha }}"
          prerelease: false
          files: "*.zip"
