name: Create Release

on:
  push:
    branches:
      - v3
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip each folder
        run: |
          for d in */ ; do
            zip -r "${d%/}.zip" "$d"
          done

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get short SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}"
          release_name: Release ${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}
          draft: false
          prerelease: false
