name: Test

on:
  push:
    branches:
      - v3
  pull_request:
    branches:
      - v3
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:stable-dind
        options: --privileged
        env:
          DOCKER_DRIVER: overlay2
          DOCKER_HOST: tcp://localhost:2375
          DOCKER_TLS_CERTDIR: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Template repo
        run: git clone --branch v3 https://github.com/CyanFox-Projects/Laravel-Template.git

      - name: Move files to modules folder
        run: |
          mkdir Laravel-Template/modules
          for file in *; do
            if [ "$file" != "Laravel-Template" ]; then
              cp -r "$file" Laravel-Template/modules/
            fi
          done

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: intl, gd, iconv, fileinfo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: |
          cd Laravel-Template/modules

          for dir in $(ls -d */); do
            cd $dir
            if [ -f "composer.json" ]; then
              /usr/local/bin/composer update
            fi
            cd ..
          done

          cd ..

          cp .env.testing .env
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          /usr/local/bin/composer update

          ./vendor/bin/sail up -d
          ./vendor/bin/sail npm install
          ./vendor/bin/sail npm run build
          ./vendor/bin/sail test
